create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  full_name text not null check (char_length(full_name) between 2 and 120),
  phone text not null check (char_length(phone) between 9 and 20),
  address text not null check (char_length(address) between 5 and 500),
  quantity integer not null default 1 check (quantity between 1 and 10),
  source text default 'voltgo-landing',
  status text not null default 'new',
  created_at timestamptz not null default now()
);
alter table public.orders enable row level security;
create policy "public can submit orders" on public.orders for insert to anon with check (true);
